version: '3'
services:
  fortunes-db:
    build: ./DATABASE/MYSQL
    image: arm64v8/mysql:latest
    container_name: fortunes-db
    volumes:
      - ./DATABASE/MYSQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fortunes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - desire

  cassandra-db:
    build:
      context: ./DATABASE/CASSANDRA
      dockerfile: Dockerfile
#    image: arm64v8/cassandra:latest
    container_name: cassandra-db
    volumes:
      - ./DATABASE/CASSANDRA/entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh
      - ./DATABASE/CASSANDRA/schema.cql:/docker-entrypoint-initdb.d/schema.cql
    ports:
      - "9042:9042"
    networks:
      - desire

  fortunes-service:
    build: ./
    image: fortunes-service
    container_name: fortunes-service
    environment:
      SPRING_APPLICATION_NAME: fortunes-service
      SPRING_DATASOURCE_URL: jdbc:mysql://fortunes-db:3306/fortunes
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_PROFILES_ACTIVE: prod

      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_CONTACT_POINT: cassandra-db
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: history
      CASSANDRA_LOCAL_DC: datacenter1
      SERVICE_REGISTRY_URL: http://service-registry:8761/eureka
    depends_on:
      - fortunes-db
      - cassandra-db
    ports:
      - "5001:8080"
    networks:
      - desire

networks:
  desire:
    external: true