-- Create database
CREATE DATABASE IF NOT EXISTS fortunes;
USE fortunes;

-- Create table
CREATE TABLE IF NOT EXISTS fortunes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    wish VARCHAR(255) NOT NULL,
    theme VARCHAR(100) NOT NULL
);


-- INSERT INTO fortunes (wish, theme) VALUES ('BRING HIM THE PHOTO', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOU WILL DIE ALONE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOU ARE THROWING YOUR LIFE AWAY', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('GO OUTSIDE!', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('ASK AGAIN LATER', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('THINK FOR YOURSELF', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('QUESTION AUTHORITY', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOU ARE WORSHIPING A SUN GOD', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('DON''T LEAVE THE HOUSE TODAY', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('GIVE UP!', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('MARRY AND REPRODUCE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('STAY ASLEEP', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('WAKE UP', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('WE WILL ALL DIE ONE DAY', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('LOOK TO LA LUNA', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('STEVEN LIVES', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('MEET STRANGERS WITHOUT PREJUDICE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('A HANGED MAN WILL BRING YOU NO LUCK TODAY', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('WHAT DO YOU WANT TO DO TODAY?', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOU ARE DARK INSIDE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('HAVE YOU SEEN THE EXIT?', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('GET A BABY PET IT WILL CHEER YOU UP.', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOUR PRINCESS IS IN ANOTHER CASTLE.', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOU ARE PLAYING IT WRONG GIVE ME THE CONTROLLER', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('TRUST GOOD PEOPLE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('LIVE TO DIE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('WHEN LIFE GIVES YOU LEMONS REROLL!', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('WELL THAT WAS WORTHLESS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('I FEEL ASLEEP!', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('MAY YOUR TROUBLES BE MANY', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOUR OLD LIFE LIES IN RUIN', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('ALWAYS LOOK ON THE BRIGHT SIDE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOU WERE BORN WRONG', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('IT IS DANGEROUS TO GO ALONE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOU WILL NEVER BE FORGIVEN', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOU HAVE NOBODY TO BLAME BUT YOURSELF', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('ONLY A SINNER', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('USE BOMBS WISELY', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('NOBODY KNOWS THE TROUBLES YOU HAVE SEEN', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('YOU LOOK FAT YOU SHOULD EXERCISE MORE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('FOLLOW THE ZEBRA', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('WHY SO BLUE?', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('THE DEVIL IN DISGUISE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('GO OUTSIDE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('ALWAYS YOUR HEAD IN THE CLOUDS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('LUCKY NUMBERS 16 31 64 70 74', 'Isaac');
--
-- INSERT INTO fortunes (wish, theme) VALUES ('EMBRACE THE UNKNOWN', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('CHALLENGE YOUR FEARS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('EVERYTHING IS A LIE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('STEP INTO THE LIGHT', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('LOOK IN THE MIRROR', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('STAY AWAKE FOREVER', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('SEEK THE TRUTH', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('IT''S NEVER TOO LATE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('STAY OR LEAVE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('LISTEN TO THE SILENCE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('CONQUER YOUR DEMONS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('NEVER SURRENDER', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('ANSWER THE CALL', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('FEAR THE SHADOWS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('FOLLOW YOUR DREAMS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('BREAK THE CHAINS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('IT''S ALL A GAME', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('HIDE YOUR SECRETS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('RISE AND FALL', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('BEWARE OF THE WOLF', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('QUESTION EVERYTHING', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('TRUST YOUR INSTINCTS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('LISTEN TO YOUR HEART', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('DON''T FEAR THE REAPER', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('LOOK BEYOND THE STARS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('TIME IS RUNNING OUT', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('NEVER LOOK BACK', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('ACCEPT YOUR FATE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('LUCKY NUMBERS  13 27 46 59 71', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('WALK THE PATH LESS TRAVELED', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('FIGHT OR FLIGHT', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('SHATTERED DREAMS  WILL MEND', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('CHASE THE DRAGON', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('BREAK FREE  FROM YOUR CHAINS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('WALK ALONE  IN THE DARK', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('COUNT YOUR BLESSINGS  NOT YOUR CURSES', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('THE PHOENIX  ALWAYS RISES', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('WHAT LIES BENEATH  IS NOT FOR YOU', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('DANCE WITH  YOUR DEMONS', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('NO PAIN  NO GAIN', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('LIFE IS A MAZE  NAVIGATE IT', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('SILENCE SPEAKS  VOLUMES', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('STARE AT THE SUN', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('FEED YOUR NIGHTMARES', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('SMILE, TOMORROW  WILL BE WORSE', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('WATCH THE CLOCK', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('DON''T BELIEVE  YOUR EYES', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('SLEEP IS  FOR THE WEAK', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('RUN TOWARDS  YOUR FEAR', 'Isaac');
-- INSERT INTO fortunes (wish, theme) VALUES ('SURRENDER  TO THE NIGHT', 'Isaac');

-- oppenheimer
INSERT INTO fortunes (wish, theme) VALUES ('NOW I AM BECOME DEATH, THE DESTROYER OF WORLDS', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your day be as illuminating as Oppenheimers breakthroughs in physics.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Like Oppenheimers discoveries, may unexpected joys manifest in your day.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your problems split as easily as an atom in Oppenheimers lab.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimer unraveled the secrets of the atom, may you unravel the secrets of your success.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your day hold the power of nuclear energy : strong, transformative, and enduring.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Just as Oppenheimer pursued knowledge, may you pursue your dreams relentlessly.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Like the atoms Oppenheimer studied, may your smallest actions lead to the most significant changes.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Just as Oppenheimer led a team of geniuses, may you inspire those around you.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your wisdom shine as bright as the first atomic test in New Mexico.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your intellect be as respected and renowned as Oppenheimers was.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimer changed the course of history, may your actions today change your life for the better.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you split your challenges as Oppenheimer split the atom.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Like the energy held in an atom, may your potential be limitless.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your courage match that of Oppenheimer, standing against the tides of his time.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimer transformed the world with his mind, may you transform your world with your vision.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you navigate the trials of your day as Oppenheimer navigated the complexities of the atom.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Like Oppenheimer, may you possess the strength to question your actions and their consequences.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your day be as impactful as Oppenheimers contributions to science.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimer sought truth in science, may you seek truth in your life.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Just as Oppenheimer never ceased to learn, may you always be open to new knowledge.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you harness your abilities to bring about positive change, just like Oppenheimer harnessed atomic energy.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As the atomic age was a testament to Oppenheimers genius, may your accomplishments attest to your abilities.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your determination be as unshakable as Oppenheimers commitment to his work.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimers work led to a new era, may your efforts today lead to a brighter tomorrow.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you be as curious and driven as Oppenheimer in his quest to understand the universe.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you foster peace and understanding, remembering Oppenheimers regrets about the atomic bombs use.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you be as groundbreaking in your field as Oppenheimer was in his.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimer played a crucial role in history, may you play a crucial role in shaping your destiny.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your contributions to the world be as profound as Oppenheimers.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimer delved into the mysteries of the atom, may you delve into the mysteries of your potential.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you show as much resilience in the face of adversity as Oppenheimer did.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Just as Oppenheimers work resonates in history, may your work resonate in your chosen field.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your day hold the promise and potential of the atomic age.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimer stood at the forefront of a new era, may you stand at the forefront of your success.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Just as Oppenheimers work led to monumental change, may your actions bring positive change in your life.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you be as persistent and dedicated as Oppenheimer was in his research.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your discoveries about yourself be as significant as Oppenheimers discoveries about the atom.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Like Oppenheimer, may you question the ethical implications of your actions.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you be as courageous in your convictions as Oppenheimer was in his pursuit of knowledge.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Like the intense focus of Oppenheimer, may your focus on your goals be unwavering.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimer faced trials with dignity, may you face your challenges with grace and perseverance.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you never stop exploring, just like Oppenheimer never stopped questioning.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your day be as fascinating and varied as Oppenheimers research.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimer left his mark on history, may you leave a mark on the hearts of those around you.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Like Oppenheimers pursuit of understanding, may you strive to understand those around you better.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('As Oppenheimer was dedicated to his work, may you be dedicated to your passion.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May your influence be as lasting as Oppenheimers legacy.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Just as Oppenheimer navigated the realm of the unseen, may you navigate through any unseen challenges today.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('May you have the courage to face the truth, just as Oppenheimer faced the truth of his creation.', 'Oppenheimer');
INSERT INTO fortunes (wish, theme) VALUES ('Just as Oppenheimers discoveries shed light on the universe, may your day be filled with enlightenment and understanding.', 'Oppenheimer');


INSERT INTO fortunes (wish, theme) VALUES ('May your day be as fabulous as Barbie''s wardrobe!', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Dream big like Barbie, and watch your wishes come true.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Embrace your uniqueness and shine like Barbie in a sea of dolls.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Let your inner Barbie sparkle and light up the world.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('May your day be filled with pink and glitter, just like Barbie''s dream house.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Be confident like Barbie, and conquer any challenge that comes your way.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Spread kindness and joy, just like Barbie''s infectious smile.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Remember to always be true to yourself, just like Barbie''s signature style.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Make every moment count, just like Barbie does in her dream careers.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Surround yourself with friends who uplift and support you, just like Barbie and her besties.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Stay positive and optimistic, just like Barbie''s outlook on life.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Live fearlessly and embrace new adventures, just like Barbie on her journeys.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Believe in the power of imagination, just like Barbie in her fantastical stories.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Make a difference in the world, just like Barbie does as a role model.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Be strong and resilient, just like Barbie in challenging situations.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Take time to pamper yourself and feel glamorous, just like Barbie getting ready for a big event.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Embrace change and growth, just like Barbie evolving throughout the years.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Be curious and eager to learn, just like Barbie exploring new interests.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Share your talents and passions with others, just like Barbie''s artistic endeavors.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Face the day with grace and elegance, just like Barbie on the runway.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Speak up for what you believe in, just like Barbie using her voice for important causes.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Celebrate every achievement, big or small, just like Barbie''s victories.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Surround yourself with positivity and good vibes, just like Barbie''s dreamy world.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Help others and be a friend in need, just like Barbie''s caring nature.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Be a leader and inspire those around you, just like Barbie in her various roles.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Find beauty in everything, just like Barbie''s appreciation for the world.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Be playful and fun-loving, just like Barbie on her endless adventures.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Face challenges with a smile and a can-do attitude, just like Barbie''s determination.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Cherish your family and friends, just like Barbie''s close bond with her sisters.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Believe in the magic of dreams, just like Barbie''s enchanting fairytales.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Be organized and stay on top of things, just like Barbie managing her busy life.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Express yourself through fashion and style, just like Barbie''s iconic looks.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Stay active and healthy, just like Barbie staying fit in her various sports.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Practice gratitude and appreciate the little things, just like Barbie counting her blessings.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Be a positive influence on those around you, just like Barbie inspiring others.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Take time to relax and recharge, just like Barbie unwinding in her dream house.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Cultivate a loving and caring heart, just like Barbie''s compassion.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Pursue your passions and never give up, just like Barbie following her dreams.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Be a role model and lead by example, just like Barbie being a positive influence.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Keep an open mind and be accepting of others, just like Barbie embracing diversity.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Laugh often and find joy in the simple pleasures, just like Barbie''s infectious laughter.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Stay humble and grateful for your blessings, just like Barbie''s down-to-earth nature.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Face challenges with creativity and problem-solving, just like Barbie''s resourcefulness.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Spread kindness like confetti, just like Barbie brightening up everyone''s day.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Be patient and understanding, just like Barbie lending a listening ear.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Celebrate your uniqueness and individuality, just like Barbie embracing her differences.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Believe in the power of friendship, just like Barbie''s unbreakable bonds.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Pursue knowledge and never stop learning, just like Barbie''s thirst for discovery.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Surround yourself with love and positivity, just like Barbie''s heartwarming stories.', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Always remember that you are fabulous just the way you are, just like Barbie, the original queen!', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('Come on, Barbie, let''s go party', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('You are Kenough', 'Barbie');
INSERT INTO fortunes (wish, theme) VALUES ('I''m a Barbie girl in a Barbie world', 'Barbie');