-- Create database
CREATE DATABASE IF NOT EXISTS fortunes;
USE fortunes;

-- Create table
CREATE TABLE IF NOT EXISTS fortunes (
        id INT AUTO_INCREMENT PRIMARY KEY,
        wish VARCHAR(255)
);

INSERT INTO fortunes (wish) VALUES ('BRING HIM THE PHOTO');
INSERT INTO fortunes (wish) VALUES ('YOU WILL DIE ALONE');
INSERT INTO fortunes (wish) VALUES ('YOU ARE THROWING YOUR LIFE AWAY');
INSERT INTO fortunes (wish) VALUES ('GO OUTSIDE!');
INSERT INTO fortunes (wish) VALUES ('ASK AGAIN LATER');
INSERT INTO fortunes (wish) VALUES ('THINK FOR YOURSELF');
INSERT INTO fortunes (wish) VALUES ('QUESTION AUTHORITY');
INSERT INTO fortunes (wish) VALUES ('YOU ARE WORSHIPING A SUN GOD');
INSERT INTO fortunes (wish) VALUES ('DON''T LEAVE THE HOUSE TODAY');
INSERT INTO fortunes (wish) VALUES ('GIVE UP!');
INSERT INTO fortunes (wish) VALUES ('MARRY AND REPRODUCE');
INSERT INTO fortunes (wish) VALUES ('STAY ASLEEP');
INSERT INTO fortunes (wish) VALUES ('WAKE UP');
INSERT INTO fortunes (wish) VALUES ('WE WILL ALL DIE ONE DAY');
INSERT INTO fortunes (wish) VALUES ('LOOK TO LA LUNA');
INSERT INTO fortunes (wish) VALUES ('STEVEN LIVES');
INSERT INTO fortunes (wish) VALUES ('MEET STRANGERS WITHOUT PREJUDICE');
INSERT INTO fortunes (wish) VALUES ('A HANGED MAN WILL BRING YOU NO LUCK TODAY');
INSERT INTO fortunes (wish) VALUES ('WHAT DO YOU WANT TO DO TODAY?');
INSERT INTO fortunes (wish) VALUES ('YOU ARE DARK INSIDE');
INSERT INTO fortunes (wish) VALUES ('HAVE YOU SEEN THE EXIT?');
INSERT INTO fortunes (wish) VALUES ('GET A BABY PET IT WILL CHEER YOU UP.');
INSERT INTO fortunes (wish) VALUES ('YOUR PRINCESS IS IN ANOTHER CASTLE.');
INSERT INTO fortunes (wish) VALUES ('YOU ARE PLAYING IT WRONG GIVE ME THE CONTROLLER');
INSERT INTO fortunes (wish) VALUES ('TRUST GOOD PEOPLE');
INSERT INTO fortunes (wish) VALUES ('LIVE TO DIE');
INSERT INTO fortunes (wish) VALUES ('WHEN LIFE GIVES YOU LEMONS REROLL!');
INSERT INTO fortunes (wish) VALUES ('WELL THAT WAS WORTHLESS');
INSERT INTO fortunes (wish) VALUES ('I FEEL ASLEEP!');
INSERT INTO fortunes (wish) VALUES ('MAY YOUR TROUBLES BE MANY');
INSERT INTO fortunes (wish) VALUES ('YOUR OLD LIFE LIES IN RUIN');
INSERT INTO fortunes (wish) VALUES ('ALWAYS LOOK ON THE BRIGHT SIDE');
INSERT INTO fortunes (wish) VALUES ('YOU WERE BORN WRONG');
INSERT INTO fortunes (wish) VALUES ('IT IS DANGEROUS TO GO ALONE');
INSERT INTO fortunes (wish) VALUES ('YOU WILL NEVER BE FORGIVEN');
INSERT INTO fortunes (wish) VALUES ('YOU HAVE NOBODY TO BLAME BUT YOURSELF');
INSERT INTO fortunes (wish) VALUES ('ONLY A SINNER');
INSERT INTO fortunes (wish) VALUES ('USE BOMBS WISELY');
INSERT INTO fortunes (wish) VALUES ('NOBODY KNOWS THE TROUBLES YOU HAVE SEEN');
INSERT INTO fortunes (wish) VALUES ('YOU LOOK FAT YOU SHOULD EXERCISE MORE');
INSERT INTO fortunes (wish) VALUES ('FOLLOW THE ZEBRA');
INSERT INTO fortunes (wish) VALUES ('WHY SO BLUE?');
INSERT INTO fortunes (wish) VALUES ('THE DEVIL IN DISGUISE');
INSERT INTO fortunes (wish) VALUES ('GO OUTSIDE');
INSERT INTO fortunes (wish) VALUES ('ALWAYS YOUR HEAD IN THE CLOUDS');
INSERT INTO fortunes (wish) VALUES ('LUCKY NUMBERS 16 31 64 70 74');

